from harbor.devops.kubesphere.local:30280/os/init_empty:1.0 

MAINTAINER zhujiahua@xiangshang360.com

COPY deploy/prd/conf/init.sh  /init.sh

COPY target/micro-eureka-0.0.1-SNAPSHOT.jar /micro-eureka-0.0.1-SNAPSHOT.jar
