server:
  port: 15092

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:14100/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.160.106:3306/xiangshang_legal_test6
    username: test_rw9
    password: test_rw9
    tomcat:
      max-active: 200
      max-wait: 10000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: SELECT 1
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  aop:
    auto: false

mybatis:
  #指定mybatis配置文件地址
  config-location: classpath:mybatis-config.xml
  #指定mybatis的Mapper文件路径
  mapper-locations: classpath:mybatis/*Mapper.xml
  #执行mybatis的Model类存放路径，进行别名映射
  type-aliases-package: com.xs.micro.up.domain.pojo.model