server:
  port: 15091
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:14100/eureka/
    prefer-ip-address: true
  instance:
    lease-expiration-duration-in-seconds: 10   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，默认90秒
    lease-renewal-interval-in-seconds: 5    #服务刷新时间配置，每隔这个时间会主动心跳一次  默认30秒
